### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by MarlaWillemse** [ImSoErgodic/py-upset#21]
Hi

I'm struggling to format my data for py-upset. 

As far as I can see from the sample data, each set is a dictionary key, and the data to be compared between sets is a series corresponding to a key. 

I created a dataframe with 2 columns-  the first containing the set name and the second containing the corresponding strings:

![image](https://user-images.githubusercontent.com/23469924/36975816-fcae8e9c-2083-11e8-971b-30860daf33c4.png)

I then created a dictionary with the set name as a key and the strings belonging to a given set as a series: 

![image](https://user-images.githubusercontent.com/23469924/36976084-f649ab76-2084-11e8-8256-cc5df5fdb46c.png)

I ran the commands: 

% matplotlib inline
import pyupset as pyu
pyu.plot(be_dict)

...and received the error: 
AttributeError: 'Series' object has no attribute 'columns'

Any help would be appreciated.

**Comment by ctSkennerton** [comment]
This is how I've formatted data for it previously https://stackoverflow.com/questions/44874835/how-can-we-format-data-like-this-pickle/46479351#46479351

I hope this also works for you

**Comment by MarlaWillemse** [comment]
Thanks, it works :)
